name: shared

networks:
  shared-network:
    external: true

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongodb-data:/data/db
      - ./dump:/docker-entrypoint-initdb.d # Seed data on first startup
      - ./scripts/mongo-init-dev.sh:/docker-entrypoint-initdb.d/mongo-init.sh # drops database and restores from docker to ensure latest data
    networks:
      - shared-network

volumes:
  mongodb-data: